Update MC version manifest url
PaperMC/paperweight pull request #154
Opened 2022-06-22 17:20 UTC by kennytv

2022-06-22 17:26 UTC, NoahvdAa commented
The create paperclip jar task should probably also be updated to use `piston-data.mojang.com`

2022-06-22 21:23 UTC, NoahvdAa approved these changes

2022-06-22 21:42 UTC, jpenilla requested changes

2022-06-22 21:42 UTC, jpenilla commented on paperweight-lib/src/main/kotlin/tasks/CreatePaperclipJar.kt
> +        val vanillaUrl = "https://piston-data.mojang.com/v1/objects/$vanillaSha1Hash/server.jar"
this should maybe use the URL from the version manifest similar to the bundler download task in InitialTasks

2022-06-22 21:43 UTC, jpenilla commented
Needs testing to check old dev bundles still work on new userdev and vice-versa, should be fine but we need to be sure.

2022-06-26 22:37 UTC, jpenilla commented on paperweight-lib/src/main/kotlin/tasks/CreatePaperclipJar.kt
> +        val vanillaUrl = "https://piston-data.mojang.com/v1/objects/$vanillaSha1Hash/server.jar"
This can possibly be addressed at a later date

2022-06-26 22:37 UTC, jpenilla approved these changes

2022-06-26 22:37 UTC, merged