Allow dev imports to pull from spigot libraries
PaperMC/paperweight pull request #168
Opened 2022-11-05 06:45 UTC by Machine-Maker

#131

2022-11-05 09:12 UTC, MiniDigger approved these changes
havent tested but this looks sane

2022-11-07 23:29 UTC, jpenilla requested changes
As mentioned internally the filtering should use the libraries txt not the result of another download, to allow the downloads to run in parallel

2022-11-10 22:34 UTC, Machine-Maker commented
Ok, switched to using the libraries txt file. Also added maven central as a fallback repo when downloading dependencies and sources for the vanilla libraries. Looks like mojang doesn't now (or never did) mirror the source jars, just the library jars.

2022-11-19 20:21 UTC, jpenilla requested changes

2022-11-19 20:21 UTC, jpenilla commented on paperweight-lib/src/main/kotlin/tasks/ApplyPaperPatches.kt
> +                librariesDirs = listOf(mcLibrariesDir.path, spigotLibrariesDir.path),
we want spigot first here in case they override a dep version

2022-11-19 20:21 UTC, jpenilla commented on paperweight-patcher/src/main/kotlin/tasks/SimpleApplyGitPatches.kt
> +        mcLibrariesDir.pathOrNull?.let { librarySources.add(it) }
again spigot sources first

2022-11-19 20:21 UTC, jpenilla commented on paperweight-lib/src/main/kotlin/util/McDev.kt
> +        librariesDirs: List<Path>?,
move this argument down one line, make it non null, and default value of `listOf()`
```kotlin
librariesDirs: List<Path> = listOf(),
```

callers will need updating ofc

2022-11-19 21:21 UTC, jpenilla approved these changes

2022-11-19 21:21 UTC, merged